---
- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item]['ansible_ssh_host'] }} {{item}}.localdomain" state=present
  with_items: groups['all']

- name: install default packages
  yum: name={{ item }} state=latest
  with_items:
    - libselinux-python
    - ntp
    - wget
    - screen
    - epel-release
    - rpm

- name: Disable selinux
  selinux: state=disabled

- name: download jdk tarball as RPM file
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
    dest: /tmp/jdk-8u131-linux-x64.rpm
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'

- name: install oracle jdk 1.8
  yum: name=/tmp/jdk-8u131-linux-x64.rpm  state=present

- name: update java alternatives setting
  alternatives: name=java link=/usr/bin/java path=/usr/java/jdk1.8.0_131/bin/java

- name: Disable transparent hugepage
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled

- name: Disable transparent hugepage defrag
  shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Ensure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes

- name: ensure firewalld is stopped and is not running at boot time.
  service: name=firewalld state=stopped enabled=no

- name: Set nofile limits
  lineinfile: dest=/etc/security/limits.conf
            insertbefore="^# End of file"
            state=present
            line="{{ item }}"
  with_items:
    - "* soft nofile 32768"
    - "* hard nofile 32768"

- name: Set nproc limits
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf
            insertafter=EOF
            state=present
            create=yes
            line="{{ item }}"
            mode=0644
  with_items:
    - "* soft nproc 32768"
    - "* hard nproc 32768"