# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
#- name: Apply common configuration to all target nodes
#  hosts: all
#  become: yes
#  become_user: root
#  roles:
#    - common

#- name: Install Ambari server
#  hosts: ambari
#  become: yes
#  become_user: root
#  roles:
#    - ambari-server
#
#- name: Install Ambari agents
#  hosts: all
#  become: yes
#  become_user: root
#  roles:
#    - ambari-agent
#
- name: Run the Blueprint
  hosts: ambari
  become: yes
  become_user: root
  roles:
    - blueprint